// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	neo4j2 "github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/application/commands"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/application/commands/handlers"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/component"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/domainentity"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/event"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/team"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/topic"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/config"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/inbound/rest"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/outbound/neo4j"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/outbound/neo4j/repositories"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/mediator"
)

// Injectors from wire.go:

func InitializeMediator() (*App, error) {
	specController := rest.NewSpecController()
	configConfig := config.NewConfig()
	driver, err := neo4j.NewNeo4jDriver(configConfig)
	if err != nil {
		return nil, err
	}
	iTeamRepository := NewTeamRepository(driver, configConfig)
	iComponentRepository := NewComponentRepository(driver, configConfig)
	iDomainRepository := NewDomainRepository(driver, configConfig)
	iTopicRepository := NewTopicRepository(driver, configConfig)
	iEventRepository := NewEventRepository(driver, configConfig)
	specValidationCommandHandler := handlers.NewSpecValidationCommandHandler(iTeamRepository, iComponentRepository, iDomainRepository, iTopicRepository, iEventRepository)
	specPersistenceCommandHandler := handlers.NewSpecPersistenceCommandHandler(iTeamRepository, iComponentRepository, iDomainRepository, iTopicRepository, iEventRepository)
	mediatorInitializer := RegisterCommandHandlers(specValidationCommandHandler, specPersistenceCommandHandler)
	app := &App{
		SpecController: specController,
		Mediator:       mediatorInitializer,
	}
	return app, nil
}

// wire.go:

type App struct {
	SpecController *rest.SpecController
	Mediator       *MediatorInitializer
}

type MediatorInitializer struct{}

var ProviderSet = wire.NewSet(config.NewConfig, rest.NewSpecController, neo4j.NewNeo4jDriver, handlers.NewSpecValidationCommandHandler, handlers.NewSpecPersistenceCommandHandler, NewTeamRepository,
	NewComponentRepository,
	NewDomainRepository,
	NewTopicRepository,
	NewEventRepository,

	RegisterCommandHandlers,
)

func RegisterCommandHandlers(
	specHandler *handlers.SpecValidationCommandHandler,
	specPersistenceHandler *handlers.SpecPersistenceCommandHandler,
) *MediatorInitializer {
	mediator.Register(commands.SpecValidationCommandName, specHandler)
	mediator.Register(commands.SpecPersictenceCommandName, specPersistenceHandler)

	return &MediatorInitializer{}
}

func NewTeamRepository(driver neo4j2.Driver, cfg *config.Config) team.ITeamRepository {
	return &repositories.TeamRepository{
		BaseRepository: &repositories.BaseRepository{
			Driver: driver,
			DbName: cfg.DBName,
		},
	}
}

func NewComponentRepository(driver neo4j2.Driver, cfg *config.Config) component.IComponentRepository {
	return &repositories.ComponentRepository{
		BaseRepository: &repositories.BaseRepository{
			Driver: driver,
			DbName: cfg.DBName,
		},
	}
}

func NewDomainRepository(driver neo4j2.Driver, cfg *config.Config) domainentity.IDomainRepository {
	return &repositories.DomainRepository{
		BaseRepository: &repositories.BaseRepository{
			Driver: driver,
			DbName: cfg.DBName,
		},
	}
}

func NewTopicRepository(driver neo4j2.Driver, cfg *config.Config) topic.ITopicRepository {
	return &repositories.TopicRepository{
		BaseRepository: &repositories.BaseRepository{
			Driver: driver,
			DbName: cfg.DBName,
		},
	}
}

func NewEventRepository(driver neo4j2.Driver, cfg *config.Config) event.IEventRepository {
	return &repositories.EventRepository{
		BaseRepository: &repositories.BaseRepository{
			Driver: driver,
			DbName: cfg.DBName,
		},
	}
}
