// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/application/commands"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/application/commands/handlers"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/component"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/domainentity"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/event"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/team"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/domain/topic"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/config"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/inbound/rest"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/outbound/neo4j"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/internal/infrastructure/outbound/neo4j/repositories"
	"github.com/saulfrancisco-ruizacevedo/event-weaver-svc/mediator"
	"github.com/saulfrancisco-ruizacevedo/go-neopersist"
)

// Injectors from wire.go:

func InitializeMediator() (*App, error) {
	specController := rest.NewSpecController()
	configConfig := config.NewConfig()
	dbRunner, err := neo4j.NewNeo4jExecutor(configConfig)
	if err != nil {
		return nil, err
	}
	persistenceManager := neopersist.NewPersistenceManager(dbRunner)
	iTeamRepository, err := NewTeamRepository(persistenceManager)
	if err != nil {
		return nil, err
	}
	iComponentRepository, err := NewComponentRepository(persistenceManager)
	if err != nil {
		return nil, err
	}
	iDomainRepository, err := NewDomainRepository(persistenceManager)
	if err != nil {
		return nil, err
	}
	iTopicRepository, err := NewTopicRepository(persistenceManager)
	if err != nil {
		return nil, err
	}
	iEventRepository, err := NewEventRepository(persistenceManager)
	if err != nil {
		return nil, err
	}
	specValidationCommandHandler := handlers.NewSpecValidationCommandHandler(iTeamRepository, iComponentRepository, iDomainRepository, iTopicRepository, iEventRepository)
	specPersistenceCommandHandler := handlers.NewSpecPersistenceCommandHandler(iTeamRepository, iComponentRepository, iDomainRepository, iTopicRepository, iEventRepository)
	mediatorInitializer := RegisterHandlers(specValidationCommandHandler, specPersistenceCommandHandler)
	app := &App{
		SpecController: specController,
		Mediator:       mediatorInitializer,
	}
	return app, nil
}

// wire.go:

type App struct {
	SpecController *rest.SpecController
	Mediator       *MediatorInitializer
}

type MediatorInitializer struct{}

var ProviderSet = wire.NewSet(config.NewConfig, rest.NewSpecController, neo4j.NewNeo4jDriver, neo4j.NewNeo4jExecutor, neopersist.NewPersistenceManager, handlers.NewSpecValidationCommandHandler, handlers.NewSpecPersistenceCommandHandler, NewTeamRepository,
	NewComponentRepository,
	NewDomainRepository,
	NewTopicRepository,
	NewEventRepository,

	RegisterHandlers,
)

func RegisterHandlers(
	specHandler *handlers.SpecValidationCommandHandler,
	specPersistenceHandler *handlers.SpecPersistenceCommandHandler,
) *MediatorInitializer {
	mediator.Register(commands.SpecValidationCommandName, specHandler)
	mediator.Register(commands.SpecPersictenceCommandName, specPersistenceHandler)
	return &MediatorInitializer{}
}

func NewTeamRepository(manager *neopersist.PersistenceManager) (team.ITeamRepository, error) {
	return repositories.NewTeamRepository(manager)
}

func NewComponentRepository(manager *neopersist.PersistenceManager) (component.IComponentRepository, error) {
	return repositories.NewComponentRepository(manager)
}

func NewDomainRepository(manager *neopersist.PersistenceManager) (domainentity.IDomainRepository, error) {
	return repositories.NewDomainRepository(manager)
}

func NewTopicRepository(manager *neopersist.PersistenceManager) (topic.ITopicRepository, error) {
	return repositories.NewTopicRepository(manager)
}

func NewEventRepository(manager *neopersist.PersistenceManager) (event.IEventRepository, error) {
	return repositories.NewEventRepository(manager)
}
